### ISSUE TITLE
Glossary - Procurement project

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#141] opened 2018-09-06 06:47 UTC
Suggestions:
Suggested:

Term: Procurement project
Definition: 

Following our conceptual meeting of 05/09/2018. It was decided that procurement project was not abstract but that a project could overarching collection of  several procedures/lots. This will discussed further on 07/09/2018.  The task of providing a draft definition was assigned to Giampaolo Sellitto but anyone is free to provide suggestions for discussion on 07/09/2018.

**Comment by JachymHercher** [comment] 2018-09-06 07:08
Do we actually want to model a "procurement project" or just a "project"? During the call we discussed examples such as airports, which to me sound rather like a "project", so I'd suggest just that. Since it's not procurement specific, the definition could come for example from the Cambridge Dictionary: 

> a piece of planned work or an activity that is finished over a period of time and intended to achieve a particular purpose:

such a project would probably "include" 0...n "lots" and that's it. 

However, there's a problem: if we include things which are not directly about procurement (e.g. "project" in the sense of "airport"), then we might need to differentiate this somehow, probably by carefully putting the word "procurement" in front of everything else.

**Comment by muricna** [comment] 2018-09-06 07:09
Linked issues #134 #140

**Comment by eprocurementontology** [comment] 2018-09-06 13:15
Suggestion from Jostein in the meeting yesterday:

Term: Procurement project
Definition: Procurement needs carried out individually or collaboratively that is carefully planned to achieve a particular aim.

**Comment by JachymHercher** [comment] 2018-09-06 14:49
I'm not sure "needs" can be "carried out". Aren't they rather measures/collected/established? 

"Individually or collaboratively" seems a bit ambiguous - is it about the needs or about the speaker/actor? If about the needs, then, since they are quite abstract, I'm not quite sure how practically one need and multiple needs are separated.

**Comment by GiampaoloSellitto** [comment] 2018-09-06 21:15
Proposal for Procurement project:
 **a systemic set of linked procurement activities aimed at achieving a common result** 
The concept of procurement project is intended ass an hub that ties together different procurement procedures 
Each procedure can have its own contracting authority, method of awarding, localization and timeline.
The procurement project will have its own nature and type (realization of public works, purchase of goods, granting of commodities to production units, etc.), field of intervention, specific localization,
financial coverage, prevalent economic activity sector of the beneficiary of public investment.

It makes sense to distinguish the project as an entity in its own, since the localization of the project can be broader than the localization of the single procedures, the project can span a much longer period of time and the object of the procurement project is in general broader that the object of the procedures that are part of it. The project is more than the sum of the procurement procedures, since it describes the value of the investments for the  stakeholders and beneficiaries.

e.g. an airport is much more than a set of Hangars, a Terminal, a Control Tower, some taxiways and a runway since each of these components would have no value if it is not placed in the coordinated context of the airport.

Even the Contracting Authorities that procure the goods that are part of the project can be different.

**Comment by GiampaoloSellitto** [comment] 2018-09-06 21:26
possible use  cases:
Public Open Data: the existence of a Procurement Project makes it easier to follow financial flows and public investments, since it makes evident the conceptual links  between different procedures - this information would not be available elsewhere in a structured format if we do not let the CA specify that a procedure is launched in the context of some project.

Oversight of Public procurement: the existence of a procurement project makes easier to oversight and catch interferences between different procedures that are part of a project but are executed by different contractors. It provides also a connection between procedures that are set up in different periods.

connections between public procurement and funding: procedures that are part of the same EU programme can be  put under  the same Procurement project, that will act as an umbrella.

**Comment by GiampaoloSellitto** [comment] 2018-09-06 21:30
Competency questions:

give me all the procedures that were set up to design, build and maintain TAP pipeline 
give me all the procedures that were financed by H2020 programme
give me all the projects that received a supply of concrete from Lot XXX$4544X

**Comment by GiampaoloSellitto** [comment] 2018-09-06 21:32
The relation between projects and procedures could be N:M since a lot can serve different projects and a project is usually realized through a multiplicity of lots

**Comment by paulakeen** [comment] 2018-09-07 06:43
From the ontology perspective, not qualifying the classes, e.g. "Project" instead of "Procurement Project", is not a problem provided that the class belongs to the ePO namespace; meaning by this that if the class is defined in the context of eProcurement and is well identfied (e.g. with a prefix representing the namespace of the eProcurement Domain, then that concept is of the Domain. Additionally it can be mapped to other domain ontologies whenever their semantic fields match to a certain degree or the individuals of those classes can be considered one the "sameAs" the other.

**Conclusion**: we can keep "Project" in the domain of ePo (which would be represented as epo:Project).

**Comment by paulakeen** [comment] 2018-09-07 06:55
Regarding my previous comment:

An alternative option is that the ePO "reuses" a class Project from another existing Ontology and with that Ontology namespace prefix. If anyone of you ever identifies such an Ontology please inform back about it.

**Comment by JachymHercher** [comment] 2018-09-07 07:28
@GiampaoloSellitto, the business case is clear and sounds good. Thanks a lot. 

I have one problem with the definition - it's broad/ambiguous in the sense that it could just as well be used for procedure (#113) or lot (#139). I would suggest using a very similar definition for all three and just indicating that they are at a different level. Thus, for project, I would suggest

> A series of activities aiming to conclude several public contracts across multiple procedures 

~~(Note: I would think we don't need to say "across multiple lots", because if the multiple lots would all be in one procedure than the project would be identical to a procedure.)~~

@paulakeen epo:Project/Procurement project is fine. We should just be aware that "airport" is not a correct example of epo:Project, "(some subset of) procurement activities done within the construction of an airport" would be a correct example.

**Comment by paulakeen** [comment] 2018-09-07 07:48
@Jachym: the definition "A series of activities aiming to conclude several public contracts across multiple procedures" leaves out those projects that are concluded by on public contract in one single procedure. I would say that those cases do exist, too. So I propose this other one:

"A series of activities aiming to conclude one or several public contracts across one or multiple procedures."

**Comment by JachymHercher** [comment] 2018-09-07 08:55
Yep, you're right. There could be a project which corresponds to lot 1,2,3 of Procedure A; there could be a project which corresponds to Lot 1 of Procedure A; there could be a project which corresponds to Procedure A. (I'd just replace "across one or multiple" with "within one or across multiple")

(In the cases that project = a procedure, or project = a lot, the added value of calling the procedure/lot also a project seems to be pretty negligible. But that' doesn't mean we can't model it.)

Review:
- Procedure: A series of activities aiming to conclude one or more public contracts.
- Lot:            A series of activities aiming to conclude all or some public contracts within a procurement procedure.
- Project:      A series of activities aiming to conclude one or more public contracts within one procedure or across multiple procedures.

According to the definitions, a lot might be a procedure and a project might be a lot or a procedure. That sounds fine. 

However, I still see a problem that, according to the definitions, any lot or a project is also a procedure, which is not the case. Thus, I would update the definition of a procedure with the only thing that I think makes it a procedure:
- Procedure: A series of activities aiming to conclude one or more public contracts. Together, these activities establish a particular legal regime for all the activities (e.g. because of their total value, the type of buyer).

**Comment by GiampaoloSellitto** [comment] 2018-09-11 08:45
Proposal:
Procedure: A series of activities aiming at awarding one or more contracts.
Lot: A qualitative or quantitative subdivision of the goods, services or works to be procured, so that the procedure can be awarded to different economic operators based on their specialization or on their location.
Project: the overall societal achievement underlying  a set of contracts, awarded through one or multiple procedures, possibly over a period of time or set up by different contracting authhorities.

**Comment by GiampaoloSellitto** [comment] 2018-09-11 08:47
Sorry, the issue is still open

**Comment by GiampaoloSellitto** [comment] 2018-09-11 08:49
Proposal:
Procedure: A series of activities aiming at awarding one or more contracts.
Lot: A qualitative or quantitative subdivision of the goods, services or works to be procured, so that the procedure can be awarded to different economic operators based on their specialization or on their location.
Project: the overall strategic objective underlying a set of contracts, awarded through one or multiple procedures, possibly over a period of time or set up by different contracting authorities.

**Comment by paulakeen** [comment] 2018-09-18 10:38
During the last meeting about the Glossary the following proposals were put forward:

1. In the **Glossary and the Ontology**: rename Procurement Project as **Project Procurement** to refer to the very broad project (in alignment to the definition provided by GiampoloSelitto in the previous comment, see above).
2. In the **Ontology**: Remove the "abstract class" Procurement Project used as a parent container of the data and object properties that are common to both Procurement Procedure and Lot. The common data properties are now duplicated inside the classes "Procurement Procedure" and "Lot"; the object properties, e.g. "Procurement Value" and "Purpose" are now associated to both the Procurement Procedure and the Lot (instead of inherited, as was the case previously).

Please confirm that these were the final decision so we can close this Issue.

**Comment by JachymHercher** [comment] 2018-11-06 19:36
Just for reference, in case it is ever needed: https://www.open-contracting.org/2018/09/26/infrastructure-transparency-connecting-project-and-contracting-data/ gives some nice examples of links between "projects" and "procurement". (https://www.open-contracting.org/2018/10/03/exploring-project-identifiers-for-infrastructure-projects/ could also be partially relevant.)

The main figure, https://www.open-contracting.org/wp-content/uploads/2018/09/image4.png, seems in line with our current "project procurement" concept.

**Closed as completed** 2021-08-19 12:41 UTC
