### ISSUE TITLE
add superclass epo:ProcurementWithSpecificRequirement

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#300] opened 2021-07-19 08:44 UTC
OP-TED/model2owl#126 shows the example of prop `hasFulfillsRequirement` that cannot be named after its range since the range is nothing more specific than `skos:Concept`:
```ttl
epo:hasFulfillsRequirement
        rdfs:domain  [ a            owl:Class ;
                       owl:unionOf  ( epo:GreenProcurement epo:InnovativeProcurement epo:SocialProcurement )
                     ] ;
        rdfs:range   skos:Concept .

epo:GreenProcurement  a  owl:Class ;
        rdfs:subClassOf  [ a                   owl:Restriction ;
                           owl:minCardinality  1 ;
                           owl:onProperty      epo:hasFulfillsRequirement
                         ] .
```

If you accept OP-TED/ePO#299 then we can have:
```ttl
skos:Concept rdfs:subClassOf
  [a owl:Restriction;
    owl:onProperty skos:inScheme;
    owl:someValuesFrom skos:ConceptScheme
    owl:cardinality 1].

epo:SpecificRequirement a owl:Class, skos:ConceptScheme;
  rdfs:subClassOf skos:Concept,
    [ a owl:Restriction ;
      owl:onProperty skos:inScheme;
      owl:hasValue epo:SpecificRequirement].

epo:specificRequirement a owl:ObjectProperty;
  rdfs:domain epo:ProcurementWithSpecificRequirement;
  rdfs:range epo:SpecificRequirement.

epo:ProcurementWithSpecificRequirement a owl:Class; 
  rdfs:subClasOf epo:Procurement;
    [ a owl:Restriction ;
      owl:onProperty epo:specificRequirement;
      owl:minCrdinality 1].

epo:GreenProcurement      a owl:Class; rdfs:subClassOf epo:ProcurementWithSpecificRequirement.
epo:InnovativeProcurement a owl:Class; rdfs:subClassOf epo:ProcurementWithSpecificRequirement.
epo:SocialProcurement     a owl:Class; rdfs:subClassOf epo:ProcurementWithSpecificRequirement.
```
Now you see how:
- we use a specific prop name `specificRequirement` that mirrors its range
- we avoid the use of `owl:unionOf` in domain because we've extracted the requirement in a common superclass `epo:ProcurementWithSpecificRequirement`

HOWEVER, you may want to be more specific and make distinct thesauri (GreenRequirement, InnovativeRequirement, SocialRequirement): then further ontological constructs will be needed.

**Comment by giorgialodi** [comment] 2021-07-19 08:57
@VladimirAlexiev we have already a superclass for the green, social and innovative procurement that is named StrategicProcurement, which is, I think, a terminology coming from the reference EU directive. And we definitely have distinct controlled vocabularies for Green, Innovative and Social requirements.

**Comment by VladimirAlexiev** [comment] 2021-07-19 09:09
@giorgialodi Can you show here the modeling used to distinguish between  Green, Innovative and Social requirements?

**Comment by giorgialodi** [comment] 2021-07-19 09:42
<img width="929" alt="Screenshot 2021-07-19 at 11 39 45" src="https://user-images.githubusercontent.com/24624577/126139878-ebe38508-5cd9-4a68-b869-41983a8c4b6d.png">

**Comment by eprocurementontology** [comment] 2021-07-20 14:19
As you can see from Giorgia's reply there is a superclass "StrategicProcurement".  We agree this is not the cleanest modelling but we are trying to align with the procurement directives as they are today and to leave a margin for future evolutions of this specific area of the procurement domain.
We are closing this issue but please feel free to reopen it if the issue is not properly addressed.

**Closed as completed by eprocurementontology** 2021-07-20 14:19 UTC

**Comment by VladimirAlexiev** [comment] 2021-07-20 19:52
StrategicProcurement is a great name. But the correlation of subclass to concept scheme needs to be captured somehow, see OP-TED/ePO#299
