### ISSUE TITLE
Standard form F13 field IV.1.9: Criteria for evaluation of projects submitted for a design contest

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ePO#450] opened 2023-06-16 11:06 UTC
EPO 3.1.0 seem to not provide an appropriate model to represent the **evaluation criteria** for design contests (field IV.1.9 of standard [form F13](https://simap.ted.europa.eu/documents/10184/99173/EN_F13.pdf)):

![image](https://github.com/OP-TED/ePO/assets/2441046/a26edab1-7880-4268-9f25-e176c4f75015)

Related to https://github.com/OP-TED/ted-rdf-mapping/issues/354

**Comment by andreea-pasare** [comment] 2023-08-16 15:14
Closing ticket as is duplicate of #456

**Closed as completed by andreea-pasare** 2023-08-16 15:14 UTC
Labels: aux: mapping
