### ISSUE TITLE
Procurement Criterion

### ISSUE THREAD

**Issue by JachymHercher** [OP-TED/ePO#203] opened 2019-06-05 11:38 UTC
The https://github.com/eForms/eForms/issues/119#issuecomment-476731892 discussion, opened a couple of months ago, may require some changes in the Procurement Criterion part of the ontology.

**Comment by paulakeen** [comment] 2019-06-06 14:45
Dear Jachym,

we have a nice proposal for you that combine the best of both worlds. We'll present it on Tuesday the  11th of June, and of course any interested parties may also participate in this meeting, from 14:30 to 16:30 at [https://ecwacs.webex.com/meet/nmuric](https://ecwacs.webex.com/meet/nmuric).

**Comment by JachymHercher** [comment] 2019-06-06 15:02
The issue is quite complicated and it might be better to have time to analyse and think about it. Could you post it beforehand here please?

**Comment by jseguraf** [comment] 2019-06-12 16:26
Last Tuesday, the 11th June, we did a brainstorming about this issue during the Working Group meeting.

As an outcome of this brainstorming we confirmed that this concept of Dimension is actually needed for the Award Criteria (concretely Price, Quality and Cost). In the ePO this “dimension concept” was modelled as a class associated to the Award Criterion. Your opinion was this class was not necessary as any attribute of the dimension was also defined in criterion (e.g. weight, threshold, formula, etc.). We quite agreed to that opinion, but for the attribute “Fixed Price” in the dimension. 

The general conclusion was that the “dimension” is yet another criterion, as all the attributes are the ones of the “ccev:Criterion” class. This “dimension” criterion can be seen as a super-criterion (a base class) that is referred to by one or more sub-criteria (descendant classes). This approach simplifies the model but implies that the sub-criteria somehow document (inform about) how they relate to the parent dimension criterion.

So, after discussion the following modelling decisions made were:

1.	We moved the “Fixed Price” attribute to the Award Criterion Class,
2.	We deleted the dimension-related class from the ontology (see diagram “Procurement Criterion”),
3.	The relation of each sub-criterion with the parent dimension is established through the object property “has Parent Criterion Relation”, which points at a code list “epo:evaluation-dimension” (codes price, cost, quality). 

On Tuesday 18th June we should review this approach and pending possible issues related to it, like, for instance:

1-	Do you think this new approach is coherent? 
2-	Can an award criterion be related to more than one dimension? E.g. a price criterion can also simultaneously be considered a quality criterion, as was suggested in the first F2F meeting?
3-	Should the relations between children and parent be disjoint or not? i.e. can you think of a situation where two or more codelists could contain different “dimensions” of one individual of criterion? 
4-	Other possible issues not identified so far.

The figure below shows how the ePO diagram looks like after the modifications explained above:
 
![Procurement Criterion](https://user-images.githubusercontent.com/33545990/59368911-8aa47300-8d3f-11e9-9ba2-320130480e25.jpg)


We would be very grateful if you can provide feedback before the next Thursday  20th June. Any interested party may is more than welcome and can freely participate in the discussions, from 14:30 to 16:30, on Tuesday and Thursday at https://ecwacs.webex.com/meet/nmuric.

**Comment by JachymHercher** [comment] 2019-06-13 09:50
1. It looks better. Still very complex, so hard to say whether fully coherent.
2. No. (At least under eForms definitions, where price is the acquisition price; cost is any other non-price monetary criterion" and the rest (quality) is "non-price non-cost").
3. Yes, it should be disjoint. These are simply three different lists: the type of exclusion grounds, types of selection criteria, types of award criteria. 

    While I don't doubt it's possible, I'm not sure that speaking about parent criteria is helpful. It sounds very complicated, what does it add? For example, is "has Parent Criterion Relation" really the simplest possible predicate? Couldn't we simply say "has Award Criterion Type", analogously to the "has Selection Criterion Type" and "has Exclusion Ground Type"? Why aren't these relationships analogous? 

Other comments:

4. "Dimension" is a technical-sounding word, not used in the Directives. Personally, I find it confusing rather than clarifying. Couldn't the evaluation-dimension codelist simply be called "award-criterion-type"? This would be identical to eForms and analogous to Selection Criterion Type. 
4. In criterion, there is no evaluation-dimension property (corresponding to the codelist). At the same time, there is a "type" property with no codelist. 
5. Evaluation Method Type should be removed, I agree with the comment in the diagram.
6. Issues 2. and 6. from https://github.com/eForms/eForms/issues/119#issuecomment-476758963 have not been resolved. 
8. What is the "Objective" indicator in Criterion?

**Comment by jseguraf** [comment] 2019-06-27 08:43
The last 13th July we had a new session to discuss about the issue. As an input, we analyse your reply and after the discussion the following modelling decisions made were: 

- The dimension code list has been renamed by “award-criterion-type”.

- Following your comment regarding the “evaluation-dimension” property, it has been renamed by “subcriterion is Of Type”.

- The “Evaluation Method Type” has been removed.

- The[ eForms/eForms#119 (comment)](https://github.com/eForms/eForms/issues/119#issuecomment-476758963) has been addressed.

**Comment by paulakeen** [comment] 2019-07-11 14:12
Let's close the issue. We think we addressed all the aspects pointed out by Jachym. In case of more reactions please ask for its re-opening.

**Closed as completed by paulakeen** 2019-07-11 14:12 UTC
